#!/usr/bin/env python3

from helpers import get_user_timeline
import sys
import os
from termcolor import colored
from analyzer import Analyzer

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
            
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    analyzer = Analyzer(positives, negatives)
    
    tweets = get_user_timeline(sys.argv[1], 30)
    if tweets == None:
        sys.exit("User profile does not exist or is private")
    
    for tweet in tweets:
        result = analyzer.analyze(tweet)
        if result > 0.0:
            print(colored(" {} {}".format(result, tweet), "green"))
        elif result < 0.0:
            print(colored(" {} {}".format(result, tweet), "red"))
        else:
            print(colored(" {} {}".format(result, tweet), "yellow"))
        
        
if __name__ == "__main__":
    main()